/*
 * Copyright 2023 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.emcstfe.models.response.getSubmissionFailureMessage

import uk.gov.hmrc.emcstfe.models.response.ErrorResponse.UnknownFunctionalErrorCode

object FunctionalErrorCodes {

  lazy val codeMap: Map[String, String] = Map(
    "4401" -> "Incorrect (code) value. Value of an element in a message is outside the predefined domain or not part of the applicable code list.",
    "4402" -> "Duplicate LRN The LRN is already known and is therefore not unique according to the specified rules",
    "4403" -> "Invalid or missing Consignor on SEED",
    "4404" -> "Invalid or missing Place of Dispatch on SEED",
    "4405" -> "Invalid or missing Consignee on SEED",
    "4406" -> "Invalid or missing Place of Delivery on SEED",
    "4407" -> "For Temporary Registered Consignee the EPC and product amounts exceed the allowed amounts on SEED",
    "4408" -> "The link between the nature of goods on the draft movement and those allowed for the consignor as held on SEED is missing or invalid",
    "4409" -> "The link between the nature of goods on the movement and those allowed for the consignee as held on SEED is missing or invalid",
    "4410" -> "The link between the nature of goods on the movement and those allowed for the Tax Warehouse as Place of Delivery as held on SEED is missing or invalid",
    "4411" -> "The link between the Consignor and EU 15/6 Products (Energy Products) as held on SEED is missing or invalid",
    "4412" -> "The link between the Consignee and Place of Delivery as held on SEED is missing or invalid",
    "4413" -> "The link between the Consignee and the TCA for a related Temporary Registered Consignee Trader Id as held on SEED is Pending",
    "4414" -> "The link between the Consignee and the TCA for a related Temporary Registered Consignee Trader Id as held on SEED is Already Used",
    "4415" -> "The link between the Consignee and the TCA for a related Temporary Registered Consignee Trader Id as held on SEED is Withdrawn",
    "4416" -> "The link between the Consignee and the TCA for a related Temporary Registered Consignee Trader Id as held on SEED is Cancelled",
    "4417" -> "The link between the Consignee and the TCA for a related Temporary Registered Consignee Trader Id as held on SEED is Expired",
    "4418" -> "The link between the Temporary Registered Consignees TCA number and the TRC Trader(Excise) Id as held on SEED is missing or invalid or the TRC is in the UK",
    "4419" -> "Direct Delivery is not allowed for this Consignee",
    "4420" -> "The Consignor is not authorised to trade with the quoted TCA as found on SEED",
    "4421" -> "TRC Product Codes Invalid",
    "4422" -> "Consignor is a Registered Consignor but Origin is not Import",
    "4423" -> "Registered Consignor sending to a Registered Consignee in the UK",
    "4424" -> "Origin of movement is Import but Consignor is not of type Registered Consignor",
    "4425" -> "Invalid Customs Office for Export Movement",
    "4426" -> "The Delivery Place Customs Office are not on the list of Customs offices",
    "4427" -> "The Competent Authority Dispatch Office is not on the list of Excise offices",
    "4428" -> "Excise Product Codes Invalid",
    "4429" -> "CN Codes Invalid",
    "4430" -> "Invalid Language Codes for Trader Id",
    "4431" -> "Invalid Language Codes for Fiscal Mark",
    "4432" -> "Invalid Language Codes for Designation of Origin",
    "4433" -> "Invalid Language Codes for Commercial description",
    "4434" -> "Invalid Language Codes for Brand Name of Products",
    "4435" -> "Invalid Language Codes for Seal Information",
    "4436" -> "Invalid Language Codes for Other/Complementary Information",
    "4437" -> "Invalid Member State Code",
    "4438" -> "Invalid Packages Code",
    "4439" -> "Invalid Kind of packages",
    "4440" -> "Invalid Transport Mode Code",
    "4441" -> "Invalid Transport Unit Codes",
    "4442" -> "Invalid Wine-Growing Zone",
    "4443" -> "Invalid Wine-Operation Code",
    "4444" -> "Invalid Alcohol Strength for Wine and Spirits",
    "4445" -> "Invalid Degree Plato for Beer",
    "4446" -> "Invalid Density for Energy Products",
    "4447" -> "Invalid Number of Packages for a countable flag",
    "4448" -> "Invalid Country Code",
    "4449" -> "Invalid Mix of Product and CN Codes",
    "4450" -> "Reserved code",
    "4451" -> "Invalid Customs Office of Import",
    "4452" -> "Maximum Journey Time Exceeded",
    "4453" -> "No Destination Change Detected",
    "4454" -> "Movement status invalid for CoD",
    "4455" -> "Consignee role invalid",
    "4456" -> "Place of Delivery Type invalid",
    "4457" -> "Consignor Role Invalid",
    "4458" -> "Place of Dispatch Type invalid",
    "4459" -> "Invalid Language Codes for Transport Arranger",
    "4460" -> "Invalid Language Codes for New Transport Trader",
    "4461" -> "Consignor does not use or manage Place of Dispatch",
    "4462" -> "Delivery Place Trader group should not be present",
    "4463" -> "Delivery Place Trader group is required",
    "4464" -> "Destination Office group should not be present",
    "4465" -> "Destination Office group is required",
    "4466" -> "Consignee Trader ID should not be present",
    "4467" -> "Consignee Trader ID is required",
    "4468" -> "Delivery Place Trader ID should not be present",
    "4469" -> "Delivery Place Trader ID is required",
    "4470" -> "Delivery Place Trader Name should not be present",
    "4471" -> "Delivery Place Trader Name is required",
    "4472" -> "Delivery Place Trader Street Name/Postcode/City should not be present",
    "4473" -> "Delivery Place Trader Street Name/Postcode/City is required",
    "4474" -> "Invalid Unsatisfactory Reason Code",
    "4475" -> "The Body Record Unique Reference entered must be unique and must match a value on the movement. Please amend your entry.",
    "4476" -> "Consignee Excise id on the IE818 does not match the Consignee Excise id on the Movement",
    "4477" -> "Place of delivery ID on the IE818 does not match the place of delivery ID on the Movement",
    "4478" -> "Date of Arrival of Excise Products on the IE818 must not be earlier than Date of Dispatch on the Movement",
    "4479" -> "Excise Product Code on IE818 does not match that on the movement for this Body Item",
    "4480" -> "Quantity of Observed Shortage or Excess exceeds Current Quantity on the Movement",
    "4481" -> "Refused Quantity is invalid",
    "4482" -> "Explanation Code does not match with any value held on Code List 51",
    "4483" -> "Complementary Information LNG field must be set to ‘en’",
    "4484" -> "Submitter ID should indicate that message is from a “GB” Consignee",
    "4485" -> "Submitter ID does not match Consignee ID on the Movement",
    "4486" -> "Message Role does not match with any value held on Code List 73",
    "4487" -> "Where the Explanation Code is Other the Complementary Information cannot be blank",
    "4488" -> "Submitter ID does not match Consignor ID on the Movement",
    "4489" -> "Submitter of the Cancel does not match Consignor on the Movement",
    "4490" -> "Unknown arc - the arc of the received message is not known",
    "4491" -> "The Date of Dispatch must not be in the past",
    "4492" -> "Message out of sequence - the message can not be processed because the receiver is not in a proper state",
    "4493" -> "Cancellation Reason Code does not match with any value held on Code List 43",
    "4494" -> "Movement status invalid for cancellation",
    "4495" -> "Cancellation is not allowed where the Movement is an Import Type ie. where the Origin Type Code is 2",
    "4496" -> "Submitter of this message does not match the Consignor ID on the movement",
    "4497" -> "Submitter of this message does not match the Consignee ID on the movement",
    "4498" -> "Movement status invalid for Report of Receipt",
    "4499" -> "SEED Unavailable Failure",
    "4500" -> "The Dispatch Import Office is not on the list of Customs Offices",
    "4501" -> "Nature of goods not allowed for splitting",
    "4502" -> "More than one new split eAD has empty destination data",
    "4503" -> "Products added on split movement",
    "4504" -> "Apart from quantities the lines on the split movements are not exactly equal to those on the original movement or partially refused where this is the case.  Or the totals of quantities are not equal.",
    "4505" -> "Intra UK movement not allowed to be split or created as a result of a split",
    "4506" -> "Unknown destination (Destination Type Code (DTC) = 8) on split movement where the original movement did not have a DTC of 8",
    "4509" -> "Split movement attempted for new destination of  Exempted Organisation  with a DTC of 5",
    "4510" -> "2 downstream movements have the same ‘Consignee Trader ID’ and ‘Place of delivery Trader ID'",
    "4511" -> "Kinds of Package field has been changed on downstream movement",
    "4512" -> "Item number changed where the content of an item on the upstream movement has been assigned to one or more downstream movements",
    "4513" -> "Transport mode not Sea or Inland Waterway on original movement",
    "4514" -> "Consignee from original movement not on a split where this is required",
    "4516" -> "Invalid Consignee Details on message",
    "4517" -> "Movement status invalid for Alert/Reject Message",
    "4518" -> "Consignee on the Alert/Reject (IE819) does not match Consignee on the movement",
    "4519" -> "Movement status invalid for Split Movement",
    "4520" -> "The New Consignee Trader information must not be present where the destination of the split is unknown",
    "4521" -> "The New Consignee Trader information must be present unless the destination of the split is unknown",
    "4522" -> "Version of the Movement status invalid for Explanation for Shortage or Excess Message",
    "4523" -> "Consignor Trader Excise Number does not match Consignor ID on the Movement",
    "4524" -> "Consignee Trader ID does not match Consignee ID on the Version of the Movement",
    "4525" -> "Invalid Dispatch Import Office",
    "4526" -> "Excise Product Code on IE871 does not match that on the movement for this Body Item",
    "4527" -> "The link between the nature of goods on the draft movement and those allowed for the Tax Warehouse as Place of Dispatch as held on SEED is missing or invalid",
    "4528" -> "Movement cannot be cancelled because it has been split",
    "4529" -> "The movement does not have ‘Deferred Indicator’ set",
    "4530" -> "The Date of Dispatch must not be in the future",
    "4531" -> "Alert or Rejection of E-AD Reason Code does not match with any value held on Code List 22",
    "4534" -> "Rule 28: Either street name, street number, postcode or city must have changed for the delivery place.",
    "4600" -> "The submitting Trader must be an Authorised Warehouse Keeper or 'Registered Consignor'",
    "4601" -> "Rule 216: transport mode must be either 1(sea transport) or 7 (Fixed transport intallations) if guarantor type code = 5.",
    "4602" -> "Rule 215: guarantor type code 5 can only be used for an energy product",
    "4603" -> "Rule 18: EORI can only be entered when the destination type code relates to an export."
  )

  def apply(errorCode: String): String = codeMap.get(errorCode) match {
    case Some(value) => value
    case None => throw UnknownFunctionalErrorCode(errorCode).throwError
  }
}
